import type { Metadata } from 'next'
import { buildMetadata, guideKeywords } from '@/lib/seo'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { guides } from '@/data/siteData'
type GuideRecord = { slug: string; title: string; category: string; excerpt: string; readTime: string; content?: string }
import Arrow from '@/components/ui/Arrow'
import SchemaScript from '@/components/ui/SchemaScript'
import { generateArticleSchema, graphSchema, webPageSchema } from '@/lib/schema'
import MarkdownLite from '@/components/ui/MarkdownLite'
export function generateStaticParams() { return guides.map((g) => ({ slug: g.slug })) }

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const g=guides.find(x=>x.slug===slug); if(!g)return{}; return buildMetadata({title:g.title.replace(' — ', ': '), description:g.excerpt, path:`/ethiopia-travel-guide/${g.slug}`, keywords:guideKeywords(g.title, g.category), type:'article'}) }
export default async function GuidePage({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const g = guides.find(x => x.slug === slug) as GuideRecord | undefined; if (!g) { notFound() } const path=`/ethiopia-travel-guide/${g.slug}`; const schema=graphSchema([webPageSchema({path,name:g.title,description:g.excerpt,breadcrumb:[{name:'Home',url:'/'},{name:'Ethiopia Travel Guide',url:'/ethiopia-travel-guide'},{name:g.title,url:path}]}),generateArticleSchema({title:g.title,slug:g.slug,description:g.excerpt,section:'Ethiopia Travel Guide'})]); return <><SchemaScript data={schema}/><section className="bg-volcanic px-6 pb-24 pt-44 text-ivory md:px-12 md:pt-52"><div className="mx-auto max-w-container"><p className="label-eyebrow">{g.category} · {g.readTime}</p><h1 className="mt-6 max-w-5xl font-display text-display-xl font-light leading-none">{g.title}</h1><p className="mt-8 max-w-2xl font-body text-body-md text-ivory/60">{g.excerpt}</p></div></section><article className="section-padding bg-ivory"><div className="container-max grid gap-14 lg:grid-cols-[0.68fr_1fr]"><aside><p className="label-eyebrow">Sawla field guide</p><h2 className="mt-5 font-display text-display-md font-light text-volcanic">Practical advice becomes stronger when tied to your actual route.</h2><p className="mt-6 font-body text-sm leading-7 text-warmgrey">Use this guide as a planning foundation, then let Sawla refine the timing, routing, permits, packing and field expectations around your season and interests.</p><Link href="/enquire" className="btn-primary-dark mt-9">Ask a Specialist <Arrow /></Link></aside><div className="max-w-prose"><MarkdownLite content={g.content || g.excerpt} /></div></div></article><section className="bg-volcanic px-6 py-24 text-center text-ivory"><p className="label-eyebrow">Private planning</p><h2 className="mx-auto mt-5 max-w-3xl font-display text-display-md font-light">Turn this guide into a route that works on the ground.</h2><Link href="/trip-finder" className="btn-primary-ivory mt-9">Use the Trip Finder <Arrow /></Link></section></>}
