import type { Metadata } from 'next'
import { buildMetadata, speciesKeywords } from '@/lib/seo'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { species, destinations } from '@/data/siteData'
import Arrow from '@/components/ui/Arrow'
import SchemaScript from '@/components/ui/SchemaScript'
import { generateSpeciesSchema, graphSchema, webPageSchema } from '@/lib/schema'
export function generateStaticParams() { return species.map((s) => ({ slug: s.slug })) }

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const s=species.find(x=>x.slug===slug); if(!s)return{}; return buildMetadata({title:`${s.name} Ethiopia Guide`, description:s.excerpt, path:`/ethiopia-wildlife/${s.slug}`, keywords:speciesKeywords(s.name, s.latin, s.status), type:'article'}) }
export default async function SpeciesPage({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const s=species.find(x=>x.slug===slug); if(!s)notFound(); const related=destinations.filter(d=>s.where.toLowerCase().includes(d.name.toLowerCase().split(' ')[0]) || d.slug.includes('bale') || d.slug.includes('simien')).slice(0,3); const path=`/ethiopia-wildlife/${s.slug}`; const schema=graphSchema([webPageSchema({path,name:`${s.name} Ethiopia Guide`,description:s.excerpt,breadcrumb:[{name:'Home',url:'/'},{name:'Wildlife',url:'/ethiopia-wildlife/endemic-species'},{name:s.name,url:path}]}),generateSpeciesSchema({commonName:s.name,latinName:s.latin,slug:s.slug,description:s.excerpt,iucnStatus:s.status})]); return <><SchemaScript data={schema}/><section className="bg-volcanic px-6 pb-24 pt-44 text-ivory md:px-12 md:pt-52"><div className="mx-auto max-w-container"><p className="label-eyebrow">{s.status}</p><h1 className="mt-6 max-w-5xl font-display text-display-xl font-light leading-none">{s.name}</h1>{s.latin && <p className="mt-5 font-display text-3xl italic text-ivory/50">{s.latin}</p>}<p className="mt-8 max-w-2xl font-body text-body-md text-ivory/60">{s.excerpt}</p></div></section><section className="bg-ivory py-16"><div className="container-max grid gap-px bg-volcanic/10 md:grid-cols-3">{[['Where to see', s.where], ['Status', s.status], ['Population', s.population]].map(([k,v])=><div key={k} className="bg-ivory p-7"><p className="label-eyebrow">{k}</p><p className="mt-3 font-display text-2xl text-volcanic">{v}</p></div>)}</div></section><section className="section-padding bg-ivory"><div className="container-max grid gap-14 lg:grid-cols-[0.75fr_1fr]"><div><p className="label-eyebrow">Field notes</p><h2 className="mt-5 font-display text-display-md font-light text-volcanic">Sightings depend on season, altitude and guide quality.</h2><Link href="/enquire" className="btn-primary-dark mt-9">Plan Wildlife Travel <Arrow /></Link></div><div><p className="font-body text-body-md text-warmgrey">{s.excerpt}</p><div className="mt-10 grid gap-4">{related.map(d=><Link href={`/ethiopias-popular-destinations/${d.slug}`} key={d.slug} className="border border-volcanic/10 p-5 hover:border-gold"><p className="label-eyebrow">Related place</p><h3 className="mt-2 font-display text-2xl text-volcanic">{d.name}</h3></Link>)}</div></div></div></section></>}
