import type { Metadata } from 'next'
import { buildMetadata } from '@/lib/seo'
import { notFound } from 'next/navigation'
import { tourStyles, itineraries } from '@/data/siteData'
import { PremiumLinkCard } from '@/components/ui/PremiumCard'
import SchemaScript from '@/components/ui/SchemaScript'
import { graphSchema, itemListSchema, webPageSchema } from '@/lib/schema'
export function generateStaticParams() { return tourStyles.map((s) => ({ style: s.slug })) }

export async function generateMetadata({params}:{params:Promise<{style:string}>}):Promise<Metadata>{ const {style}=await params; const s=tourStyles.find(x=>x.slug===style); if(!s)return{}; return buildMetadata({title:s.name, description:`Private ${s.name.toLowerCase()} in Ethiopia with Sawla Tours: curated routes, expert guides, field logistics and custom itinerary design.`, path:`/tours-by-experience/${s.slug}`, keywords:[s.name, 'Ethiopia private tours', 'Ethiopia itinerary', 'custom Ethiopia tours', 'Sawla Tours']}) }
export default async function TourStylePage({params}:{params:Promise<{style:string}>}){ const {style}=await params; const s=tourStyles.find(x=>x.slug===style); if(!s)notFound(); const list=itineraries.filter(i=>i.style===s.slug); const path=`/tours-by-experience/${s.slug}`; const schema=graphSchema([webPageSchema({path,name:s.name,description:s.desc,type:'CollectionPage',breadcrumb:[{name:'Home',url:'/'},{name:'Tours',url:'/tours-by-experience'},{name:s.name,url:path}]}),itemListSchema({name:`${s.name} itineraries`,path,items:list.map(i=>({name:i.title,url:`/tours-by-experience/${s.slug}/${i.slug}`}))})]); return <><SchemaScript data={schema}/><section className="bg-volcanic px-6 pb-24 pt-44 text-ivory md:px-12 md:pt-52"><div className="mx-auto max-w-container"><p className="label-eyebrow">{s.number} · Tour style</p><h1 className="mt-6 max-w-5xl font-display text-display-xl font-light leading-none">{s.name}</h1><p className="mt-8 max-w-2xl font-body text-body-md text-ivory/60">{s.desc}</p></div></section><section className="section-padding bg-ivory"><div className="container-max"><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{list.map((it,i)=><PremiumLinkCard key={it.slug} href={`/tours-by-experience/${s.slug}/${it.slug}`} eyebrow={it.duration} title={it.title} text={it.overview} meta={it.priceFrom} tone={i%3===0?'gold':i%3===1?'green':'ember'} />)}</div>{list.length===0 && <div className="border border-volcanic/10 p-10"><h2 className="font-display text-3xl text-volcanic">Custom route available</h2><p className="mt-4 font-body text-warmgrey">This travel style is usually built from scratch after a planning conversation.</p></div>}</div></section></> }
